[package]
name = "droplet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
lazy_static = "1.4.0"
reqwest = { version = "0.11.22", features = ["blocking"] }
toml = "0.8.6"
